Repository gruppe-adler/gruppe_adler_mod, pull requests merged in 2018-04, with the labels that each got.

#80 Adding switchHeadgear
  optionals/switchHeadgear/$PBOPREFIX$
  optionals/switchHeadgear/CfgEventHandlers.hpp
  optionals/switchHeadgear/README.md
  optionals/switchHeadgear/XEH_PREP.hpp
  optionals/switchHeadgear/XEH_preInit.sqf
  optionals/switchHeadgear/XEH_preStart.sqf
  optionals/switchHeadgear/cfgVehicles.hpp
  optionals/switchHeadgear/config.cpp
  optionals/switchHeadgear/functions/fnc_switchGear.sqf
  optionals/switchHeadgear/script_component.hpp
Labels: enhancement, needs testing

#81 Added flag addon
  addons/flag/$PBOPREFIX$
  addons/flag/README.md
  addons/flag/cfgVehicles.hpp
  addons/flag/config.cpp
  addons/flag/data/gruppeAdlerWhite.paa
  addons/flag/script_component.hpp
  addons/flag/stringtable.xml
Labels: enhancement, ready to merge

#76 add grad_axe
  addons/axe/$PBOPREFIX$
  addons/axe/CfgEventHandlers.hpp
  addons/axe/CfgFunctions.hpp
  addons/axe/CfgWeapons.hpp
  addons/axe/README.md
  addons/axe/XEH_clientInit.sqf
  addons/axe/XEH_preInit.sqf
  addons/axe/config.cpp
  addons/axe/functions/fn_cutDownTree.sqf
  addons/axe/functions/fn_findTrunk.sqf
  addons/axe/functions/fn_interactEH.sqf
  addons/axe/functions/script_component.hpp
  addons/axe/script_component.hpp
  addons/axe/sound/chop.ogg
  addons/axe/stringtable.xml
  addons/axe/ui/action_axe_ca.paa
  addons/axe/ui/item_axe_ca.paa
Labels: enhancement, ready to merge

#70 zeus - implement Prometheus modules
  addons/zeus/CfgVehicles.hpp
  addons/zeus/README.md
  addons/zeus/UI.hpp
  addons/zeus/XEH_PREP.hpp
  addons/zeus/config.cpp
  addons/zeus/displays/RscModuleBlacklistHeadless.hpp
  addons/zeus/displays/RscModuleDiagnostics.hpp
  addons/zeus/displays/RscModuleMoveRespawn.hpp
  addons/zeus/displays/RscModuleSetLoadouts.hpp
  addons/zeus/displays/external.hpp
  addons/zeus/functions/fnc_moduleAddPlayersToZeus.sqf
  addons/zeus/functions/fnc_moduleAddPlayersToZeusServer.sqf
  addons/zeus/functions/fnc_moduleBlacklistHeadlessOnConfirm.sqf
  addons/zeus/functions/fnc_moduleMoveRespawnOnConfirm.sqf
  addons/zeus/functions/fnc_moduleReloadLoadout.sqf
  addons/zeus/functions/fnc_moduleSetLoadoutsOnConfirm.sqf
  addons/zeus/functions/fnc_moduleSetLoadoutsReapply.sqf
  addons/zeus/functions/fnc_moduleToggleBFT.sqf
  addons/zeus/functions/fnc_ui_moduleBlacklistHeadless.sqf
  addons/zeus/functions/fnc_ui_moduleMoveRespawn.sqf
  addons/zeus/functions/fnc_ui_moduleSetLoadouts.sqf
  addons/zeus/stringtable.xml
Labels: enhancement, ready to merge

#86 axe tweaks
  addons/axe/CfgFunctions.hpp
  addons/axe/functions/fn_checkCutDown.sqf
  addons/axe/functions/fn_cutDownTree.sqf
Labels: enhancement

#85 remove switchHeadgear in favor of grad_slingHelmet, close #83
  optionals/switchHeadgear/$PBOPREFIX$
  optionals/switchHeadgear/CfgEventHandlers.hpp
  optionals/switchHeadgear/README.md
  optionals/switchHeadgear/XEH_PREP.hpp
  optionals/switchHeadgear/XEH_preInit.sqf
  optionals/switchHeadgear/XEH_preStart.sqf
  optionals/switchHeadgear/cfgVehicles.hpp
  optionals/switchHeadgear/config.cpp
  optionals/switchHeadgear/functions/fnc_switchGear.sqf
  optionals/switchHeadgear/script_component.hpp
Labels: enhancement
